"""schema updated

Revision ID: 8c7cdf1edd0c
Revises: f748170ff879
Create Date: 2024-08-05 19:16:56.356884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c7cdf1edd0c'
down_revision: Union[str, None] = 'f748170ff879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_thread_user_id_prompt_id', table_name='thread')
    op.drop_index('ix_thread_prompt_id', table_name='thread')
    op.drop_index('ix_thread_question_id', table_name='thread')
    op.drop_index('ix_thread_user_id', table_name='thread')
    op.drop_table('thread')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('thread_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prompt_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], name='thread_prompt_id_fkey'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='thread_question_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='thread_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='thread_pkey')
    )
    op.create_index('ix_thread_user_id', 'thread', ['user_id'], unique=False)
    op.create_index('ix_thread_question_id', 'thread', ['question_id'], unique=False)
    op.create_index('ix_thread_prompt_id', 'thread', ['prompt_id'], unique=False)
    op.create_index('idx_thread_user_id_prompt_id', 'thread', ['user_id', 'prompt_id'], unique=False)
    # ### end Alembic commands ###
